### ISSUE TITLE
Inference script

### ISSUE THREAD

**Issue by masc-it** [Shengcao-Cao/HASSOD#1]
Hey nice job! Results seem very interesting.

Is it possible to have an inference script or a gradio demo with all the necessary to run the model?

Thanks!

**Comment by Shengcao-Cao** [comment]
Hello @masc-it,

We already have the evaluation script if you want to do inference on a dataset. Do you mean something more lightweight and easy-to-use? I will upload a demo script that can take one image as input and visualize segmentation masks.

Best,
Shengcao

**Comment by Shengcao-Cao** [comment]
Hello @masc-it,

I just pushed the code for running a demo. The instructions are in the updated README. Let me know if you have any questions!

Best,
Shengcao

**Comment by masc-it** [comment]
Thank you, really appreciated! An info: can it run on MPS?

**Comment by Shengcao-Cao** [comment]
Do you mean running on a Mac? I never tried that before because I don't have a compatible device. But I believe it should work with minimal change to the code (if necessary)
