### ISSUE TITLE
Can I use this model to train my own data set?

### ISSUE THREAD

**Issue by yaosx616** [Shengcao-Cao/HASSOD#2]
What if the dataset is about whether symmetrical images can self-supervise and generate corresponding tags, or just identify the types of objects in the picture?

**Comment by Shengcao-Cao** [comment]
Hello @yaosx425 ,

Yes, I think you can train a new model using your own dataset. Please check https://github.com/Shengcao-Cao/HASSOD/blob/main/reproduction.md and make necessary modifications to the code. Basically you will need several steps including generating the pseudo-labels and train an object detector on them.

I don't quite get your idea about the dataset. Would you mind providing more details about your customized data? Please note that our method is class-agnostic, which means that it can only discover foreground objects, but cannot identify their categories or classify the objects.

Best,
Shengcao

**Comment by yaosx616** [comment]
> Hello @yaosx425 ,
> 
> Yes, I think you can train a new model using your own dataset. Please check https://github.com/Shengcao-Cao/HASSOD/blob/main/reproduction.md and make necessary modifications to the code. Basically you will need several steps including generating the pseudo-labels and train an object detector on them.
> 
> I don't quite get your idea about the dataset. Would you mind providing more details about your customized data? Please note that our method is class-agnostic, which means that it can only discover foreground objects, but cannot identify their categories or classify the objects.
> 
> Best, Shengcao

Thank you for your patient answer. I'll try it first and look forward to its result! o(*￣▽￣*)ブ
