### ISSUE TITLE
cannot import name 'get_fed_loss_cls_weights' from 'detectron2.data.detection_utils

### ISSUE THREAD

**Issue by GFK-hpu** [Shengcao-Cao/HASSOD#3]
这个函数是自己写的么？为什么detectron2里面找不到？

**Comment by Shengcao-Cao** [comment]
Hi @GFK-hpu ,

I think this function is here: https://github.com/facebookresearch/detectron2/blob/main/detectron2/data/detection_utils.py#L550. Maybe double check your detectron2 installation?

Best,
Shengcao

**Comment by GFK-hpu** [comment]
be sorry to bother you,thank you

**Comment by Shengcao-Cao** [comment]
No worries. Best regards.
